name: CI

on: [ push, pull_request ]

jobs:
  build-and-test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
          with:
            submodules: true

      -   name: Generate build config
          run: >-
            cmake -S "${{ github.workspace }}" -B "${{ github.workspace }}/build"
            -DCMAKE_BUILD_TYPE=RelWithDebInfo

      -   name: Build
          run: >-
            cmake --build "${{ github.workspace }}/build"
            --parallel 12

      -   name: Run Tests
          working-directory: ${{ github.workspace }}/build
          run: ctest -C "Release" --verbose
