name: CI

on: [ push, pull_request ]

jobs:
  build-and-test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
          with:
            submodules: true

      -   name: Setup third_party
          run: |
            git clone https://github.com/Microsoft/vcpkg.git
            ./vcpkg/bootstrap-vcpkg.sh
            ./vcpkg/vcpkg install catch2
      -   name: Generate build config
          run: >-
            cmake -S "${{ github.workspace }}" -B "${{ github.workspace }}/build"
            -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

      -   name: Build
          run: >-
            cmake --build "${{ github.workspace }}/build"
            --parallel 12

      -   name: Run Tests
          working-directory: ${{ github.workspace }}/build
          run: ctest -C "Release" --verbose
